---
- name: Ensure promsic service file is present
  template:
    src: promisc.service.j2
    dest: /etc/systemd/system/promisc.service
    owner: root
    group: root
    mode: 0755

- name: Ensure promisc is running on startup
  systemd:
    name: promisc
    daemon_reload: yes
    state: started
    enabled: true